<div id="shipment_tracking_info_block" class="grid" style="width: auto;">

<h2><?php echo $this->__('Tracking history'); ?></h2>
<table class="data" style="width: auto;">
<thead>
  <tr class="headings">
    <th><?php echo $this->__("Event time"); ?></th>
    <th><?php echo $this->__("Code"); ?></th>
    <th><?php echo $this->__("Event description"); ?></th>
    <th><?php echo $this->__("Event location"); ?></th>
  </tr>
</thead>
<tbody class="even">
<?php
$data = $this->trackingData();
foreach($data as $key => $event):
?>
  <tr class='border'>
  <td><?php echo $this->formatTime($event->happened_at) ?></td>
  <td><?php echo $event->code ?></td>
  <td><?php echo $event->label->en ?></td>
  <td><?php echo $this->formatTrackingLocation($event->location) ?></td>
  </tr>
<?php
endforeach;
?>
</tbody>
</table>
</div>
